# Generated by Django 5.0.7 on 2024-07-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_remove_answer_user_alter_question_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentanswer",
            name="answer_text",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Answer Text"),
        ),
    ]
