# Generated by Django 5.0.7 on 2024-07-23 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_alter_material_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите раздел",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="lms.section",
                verbose_name="Раздел",
            ),
        ),
    ]
